spring:
  application:
    name: roomiehub

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/RoomieHub}
    username: ${DB_USERNAME:phoneshop_night}
    password: ${DB_PASSWORD:vichea123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # ⚠️ use 'validate' in production
    show-sql: true
    open-in-view: true   # ✅ Changed from false to true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DB:0}

  websocket:
    max-text-message-size: 8192
    max-binary-message-size: 8192

# CDN Config (Cloudinary) – replace with your actual credentialsS
cloudinary:
  cloud-name: ddpatzqpg
  api-key: 712578661853192
  api-secret: C-C6i6vsg30hC_-i7_jzMr2vxFY

# OpenAPI / Swagger UI configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    enabled: true
  api-docs:
    enabled: true

server:
  port: ${SERVER_PORT:8088}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    org.roomrental.group: DEBUG